application:
  subdomain: sublinkpro
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://sublinkpro:8000/
services:
  sublinkpro:
    # upstream: docker.io/zerodeng/sublink-pro:v1.2.15
    image: docker.1ms.run/zerodeng/sublink-pro:v1.2.15
    binds:
      - /lzcapp/var/db:/app/db
      - /lzcapp/var/template:/app/template
      - /lzcapp/var/logs:/app/logs
