application:
  subdomain: sublinkpro
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://sublinkpro:8000/

services:
  sublinkpro:
    image: docker.1ms.run/zerodeng/sublink-pro:{{if  .U.image_tag}}{{.U.image_tag}}{{else}}v1.2.7{{end}}
    binds:
      - /lzcapp/var/db:/app/db
      - /lzcapp/var/template:/app/template
      - /lzcapp/var/logs:/app/logs
